### ISSUE TITLE
As a registered user, I want to be able to rate and comment on templates so that other users can view them.

### ISSUE THREAD

**Issue by CaylaVinzons** [debkbanerji/templyte#28]
## Story/Task Details
- [ ] Add rating field to database
- [ ] Communicate rating to database
- [ ] Create Front end review page from template page
- [ ] Update My Templates page to include rating
- [ ] Update All Templates page to include rating
- [ ] Style Review Page

## Acceptance Scenarios
- Given: A registered user is viewing a template that they want to give a rating to
- When: The user chooses the rating they want to assign to the template and clicks the “submit” button
- Then: A confirmation box pops up on the screen informing the user that their rating has been submitted 

## Done Done Criteria
see std
